version: '2'

services:
    php_insere:
        container_name: autocomplete_insere_dados
        build:
            context: ./build
            dockerfile: DockerfilePHP.dev
        depends_on:
            - mysql
        volumes:
            - ./microservico_insercao_dados/:/var/www/html

    php_consulta:
        container_name: autocomplete_consulta_dados
        build:
            context: ./build
            dockerfile: DockerfilePHP.dev
        volumes:
            - ./microservico_autocomplete/:/var/www/html

    mysql:
        image: mysql:5.6
        container_name: autocomplete_banco_dados
        volumes:
            - ~/mysql_docker/autocomplete_banco_dados:/var/lib/mysql
            - "./build/backup-banco-dados:/database"
        environment:
            MYSQL_DATABASE: projeto
            MYSQL_ROOT_PASSWORD: root

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
        container_name: autocomplete_elasticsearch
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "xpack.security.enabled=false"       
        ports:
            - "9200:9200"             
        volumes:
            - ~/elasticsearch_docker/autocomplete_elasticsearch/data:/usr/share/elasticsearch/data