version: '2'

services:
    php_insere:
        container_name: autocomplete_insere_dados
        build:
            context: ./build
            dockerfile: DockerfilePHP.dev
        depends_on:
            - mysql
        volumes:
            - ./microservico_insercao_dados/:/var/www/html

    php_consulta:
        container_name: autocomplete_consulta_dados
        build:
            context: ./build
            dockerfile: DockerfilePHP.dev
        volumes:
            - ./microservico_autocomplete/:/var/www/html

    mysql:
        image: mysql:5.6
        container_name: autocomplete_banco_dados
        volumes:
            - ~/mysql_docker/autocomplete_banco_dados:/var/lib/mysql
            - "./build/backup-banco-dados:/database"
        environment:
            MYSQL_DATABASE: projeto
            MYSQL_ROOT_PASSWORD: root

    elasticsearch:
        image: elasticsearch:6.8.6
        container_name: autocomplete_elasticsearch
