version: '2'

services:
    php_sistema:
        container_name: autocomplete_sistema
        build:
            context: ./build
            dockerfile: DockerfilePHP.dev
        depends_on:
            - mysql
        volumes:
            - ./sistema/:/var/www/html

    php_consulta:
        container_name: autocomplete_consulta_dados
        build:
            context: ./build
            dockerfile: DockerfilePHP.dev
        volumes:
            - ./microservico_autocomplete/:/var/www/html

    mysql:
        image: mysql:5.6
        container_name: autocomplete_banco_dados
        volumes:
            - ~/mysql_docker/autocomplete_banco_dados:/var/lib/mysql
            - "./build/backup-banco-dados:/database"
        environment:
            MYSQL_DATABASE: projeto
            MYSQL_ROOT_PASSWORD: root

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        container_name: autocomplete_elasticsearch
        environment:
            - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
            - "xpack.security.enabled=false"     
            - "discovery.type=single-node"  
        volumes:
            - ~/elasticsearch_docker/autocomplete_elasticsearch/data:/usr/share/elasticsearch/data